### ISSUE TITLE
Error getting username and lastname in spanish

### ISSUE THREAD

**Issue by JavierDuarteC** [d3xt3r2909/linkedin_login#17]
I pushed a change to get name and last name from the user's profile depending on the first language selected.

**Comment by d3xt3r2909** [comment]
Hi @JavierDuarteC  thank you for reporting and quick https://github.com/d3xt3r2909/linkedin_login/pull/16 . I will just add a more secure option to your PR and we can merge it.

**Comment by d3xt3r2909** [comment]
Done. It should be fixed! Thanks again. 🎖️

**Comment by JavierDuarteC** [comment]
Thanks, I hope you update the pub dev package 🙂

**Comment by d3xt3r2909** [comment]
@JavierDuarteC you still have issue or? It should be updated to v1.1.2

**Comment by JavierDuarteC** [comment]
@d3xt3r2909 I'll test it, Thank you!

**Comment by JavierDuarteC** [comment]
@d3xt3r2909 v1.1.2 isnt updated. I've tested and json en_US still appears

**Comment by d3xt3r2909** [comment]
Increased version again to v1.1.3 maybe I didn't pull the code from master. Please check it now, otherwise, there is something wrong.

**Comment by JavierDuarteC** [comment]
Grat! Its done!

**Comment by d3xt3r2909** [comment]
Super, sorry for delay and thank you for using lib.

**Comment by JavierDuarteC** [comment]
Its ok, thanks. Keep up your good work!
